mysql:
  host: "localhost"
  port: 3306
  user: "user"
  password: "123456"
  database: "db_agent"

chroma:
  directory: "./chroma/data"

llm:
  chat: "gpt-4o"
  embedding: "text-embedding-ada-002"
  #chat: "gpt-3.5-turbo"
  #embedding: "text-embedding-3-small"