version: '3.8'

services:
  mysql:
    container_name: "agent-mysql"
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_agent
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - D:\\HKUST\\CourseWork\\CSIT6910D Independent Project\\personal-schedule-planning-agent\\database\\mysql\\data:/var/lib/mysql
      - D:\\HKUST\\CourseWork\\CSIT6910D Independent Project\\personal-schedule-planning-agent\\database\\mysql\\conf.d:/etc/mysql/conf.d
      - D:\\HKUST\\CourseWork\\CSIT6910D Independent Project\\personal-schedule-planning-agent\\database\\mysql\\log:/var/log